### ISSUE TITLE
Resources Freeze

### ISSUE THREAD

**Issue by GallopingTurtle** [nokyan/resources#310]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

After being awake for a while and a few system locks and unlocks, resources freezes

### Expected Behavior

Dont do that

### Steps To Reproduce

Not sure how to do so reliably. It just happens after a while during which i sometimes "lock" my computer

![image](https://github.com/user-attachments/assets/ee4c6331-396f-45ba-8353-1fd97eefa855)

### Environment

```markdown
1.5.1
Ubuntu 22.04.4 LTS
GNOME 42.9
```

### Anything else?

Got this in the logs:

```
thread 'main' panicked at src/ui/pages/applications/application_entry.rs:36:9:
property 'cpu-usage' of type 'ApplicationEntry' can't be set from given value, it is invalid or out of range
stack backtrace:
   0:     0x5d7de6267d7f - <unknown>
   1:     0x5d7de601584b - <unknown>
   2:     0x5d7de6235692 - <unknown>
   3:     0x5d7de6269e99 - <unknown>
   4:     0x5d7de62696be - <unknown>
   5:     0x5d7de626a954 - <unknown>
   6:     0x5d7de626a272 - <unknown>
   7:     0x5d7de626a1c9 - <unknown>
   8:     0x5d7de626a1b6 - <unknown>
   9:     0x5d7de60139f2 - <unknown>
  10:     0x5d7de602cb9b - <unknown>
  11:     0x5d7de61008b5 - <unknown>
  12:     0x5d7de60ffd08 - <unknown>
  13:     0x5d7de6216964 - <unknown>
  14:     0x5d7de6210ae0 - <unknown>
  15:     0x5d7de602e3fa - <unknown>
  16:     0x7b0b03bd4667 - <unknown>
  17:     0x7b0b03bd6787 - <unknown>
  18:     0x7b0b03bd6e43 - g_main_context_iteration
  19:     0x7b0b03dbc05d - g_application_run
  20:     0x5d7de6151692 - <unknown>
  21:     0x5d7de5fdb373 - <unknown>
  22:     0x5d7de5fdb751 - <unknown>
  23:     0x7b0b038c608a - <unknown>
  24:     0x7b0b038c614b - __libc_start_main
  25:     0x5d7de5fdb2a5 - <unknown>
  26:                0x0 - <unknown>
thread '<unnamed>' panicked at src/ui/window.rs:539:44:
called `Result::unwrap()` on an `Err` value: RecvError
stack backtrace:
   0:     0x5d7de6267d7f - <unknown>
   1:     0x5d7de601584b - <unknown>
   2:     0x5d7de6235692 - <unknown>
   3:     0x5d7de6269e99 - <unknown>
   4:     0x5d7de62696be - <unknown>
   5:     0x5d7de626a954 - <unknown>
   6:     0x5d7de626a272 - <unknown>
   7:     0x5d7de626a1c9 - <unknown>
   8:     0x5d7de626a1b6 - <unknown>
   9:     0x5d7de60139f2 - <unknown>
  10:     0x5d7de601a365 - <unknown>
  11:     0x5d7de61f5f3e - <unknown>
  12:     0x5d7de614ba89 - <unknown>
  13:     0x5d7de626beab - <unknown>
  14:     0x7b0b0392ce39 - <unknown>
  15:     0x7b0b039b49c4 - __clone
  16:                0x0 - <unknown>
```

**Comment by nokyan** [comment]
Hi, thanks for the issue,
I believe CPU usage calculation could go wrong after sleeping, depending on what the kernel specifically does after the device wakes up. There should be an easy workaround though by changing "special" floats like NaN to just 0.
I'll push a patch tomorrow or so.

**Comment by GallopingTurtle** [comment]
Wow! didn't think it would be that easy. thanks for the good work!
